name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main  # Runs when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Docusaurus
        run: npm run build

      - name: Set Git user
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions@github.com"

      - name: Deploy to GitHub Pages
        env:
          GIT_USER: "github-actions[bot]"
          USE_SSH: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/divyn/divyn.github.io.git
          npm run deploy
